spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/test
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mappers/*.xml
